'use client';

import {useEffect,useMemo,useState} from 'react';
type Tab='home'|'discover'|'avatar'|'profile'; type Game={name:string;players:string;genre:string};
const games:Game[]=[{name:'Brookhaven RP',players:'1.2M',genre:'Roleplay'},{name:'Blox Fruits',players:'890K',genre:'Adventure'},{name:'Fisch',players:'340K',genre:'Adventure'},{name:'Da Hood',players:'210K',genre:'Action'},{name:'Adopt Me!',players:'180K',genre:'Roleplay'},{name:'Murder Mystery 2',players:'95K',genre:'Survival'}];
const defaults={name:'Rari',display:'Rari',robux:10000,description:'welcome to my profile'};
export default function Home(){
 const[tab,setTab]=useState<Tab>('home'),[name,setName]=useState(defaults.name),[display,setDisplay]=useState(defaults.display),[robux,setRobux]=useState(defaults.robux),[description,setDescription]=useState(defaults.description),[search,setSearch]=useState(''),[sheet,setSheet]=useState<'menu'|'settings'|'edit'|null>(null),[toast,setToast]=useState('');
 useEffect(()=>{const raw=localStorage.getItem('rlp-state');if(raw){try{const x=JSON.parse(raw);setName(x.name??defaults.name);setDisplay(x.display??defaults.display);setRobux(x.robux??defaults.robux);setDescription(x.description??defaults.description)}catch{}}},[]);
 useEffect(()=>{localStorage.setItem('rlp-state',JSON.stringify({name,display,robux,description}))},[name,display,robux,description]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),1800);return()=>clearTimeout(t)}},[toast]);
 const filtered=useMemo(()=>games.filter(g=>g.name.toLowerCase().includes(search.toLowerCase())),[search]);
 return <main className="phone">
  <header className="topbar"><button className="iconBtn" onClick={()=>setSheet('menu')}>☰</button><div className="brand">◈ <span>Roblox</span></div><button className="iconBtn" onClick={()=>setSheet('settings')}>⚙</button></header>
  <section className="content">{tab==='home'&&<HomeScreen name={display} robux={robux} setTab={setTab} onEdit={()=>setSheet('edit')}/>}
   {tab==='discover'&&<Discover search={search} setSearch={setSearch} games={filtered}/>}
   {tab==='avatar'&&<AvatarScreen name={display}/>}
   {tab==='profile'&&<Profile name={name} display={display} robux={robux} description={description} onEdit={()=>setSheet('edit')}/>}</section>
  <nav className="nav"><NavButton active={tab==='home'} icon="⌂" label="Home" onClick={()=>setTab('home')}/><NavButton active={tab==='discover'} icon="⌕" label="Discover" onClick={()=>setTab('discover')}/><NavButton active={tab==='avatar'} icon="♙" label="Avatar" onClick={()=>setTab('avatar')}/><NavButton active={tab==='profile'} icon="●" label="Profile" onClick={()=>setTab('profile')}/></nav>
  {sheet==='menu'&&<Sheet title="Menu" close={()=>setSheet(null)}><SheetRow icon="♙" title="Avatar" sub="Customize your simulated avatar" onClick={()=>{setTab('avatar');setSheet(null)}}/><SheetRow icon="◉" title="Profile" sub="View your public profile" onClick={()=>{setTab('profile');setSheet(null)}}/><SheetRow icon="⚙" title="Settings" sub="Simulator preferences" onClick={()=>setSheet('settings')}/></Sheet>}
  {sheet==='settings'&&<Sheet title="Settings" close={()=>setSheet(null)}><div className="setting"><span>Simulator mode</span><b>ON</b></div><div className="setting"><span>Local persistence</span><b>ON</b></div><button className="wideBtn" onClick={()=>{localStorage.removeItem('rlp-state');location.reload()}}>Reset simulated account</button></Sheet>}
  {sheet==='edit'&&<Sheet title="Edit Profile" close={()=>setSheet(null)}><label className="field">Username<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Display name<input value={display} onChange={e=>setDisplay(e.target.value)}/></label><label className="field">Robux<input type="number" min="0" value={robux} onChange={e=>setRobux(Math.max(0,Number(e.target.value)||0))}/></label><label className="field">About<input value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="primaryBtn" onClick={()=>{setToast('Profile saved');setSheet(null)}}>Save changes</button></Sheet>}
  {toast&&<div className="toast">{toast}</div>}
 </main>
}
function NavButton({active,icon,label,onClick}:{active:boolean;icon:string;label:string;onClick:()=>void}){return <button className={'navBtn '+(active?'active':'')} onClick={onClick}><span>{icon}</span><small>{label}</small></button>}
function HomeScreen({name,robux,setTab,onEdit}:{name:string;robux:number;setTab:(t:Tab)=>void;onEdit:()=>void}){return <><div className="hero"><div><p className="eyebrow">WELCOME BACK</p><h1>{name}</h1><p className="muted">What are you playing today?</p></div><div className="balance"><span>R$</span>{robux.toLocaleString()}</div></div><SectionTitle title="Continue" action="See All" onClick={()=>setTab('discover')}/><div className="gameScroller">{games.slice(0,4).map(g=><GameCard game={g} key={g.name}/>)}</div><SectionTitle title="Recommended" action="See All" onClick={()=>setTab('discover')}/><div className="list">{games.slice(2).map(g=><GameRow game={g} key={g.name}/>)}</div><button className="editBar" onClick={onEdit}>✎ <span>Edit simulated account</span><b>›</b></button></>}
function Discover({search,setSearch,games}:{search:string;setSearch:(s:string)=>void;games:Game[]}){return <><h1>Discover</h1><div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search experiences"/></div><div className="chips"><span className="chip selected">For You</span><span className="chip">Popular</span><span className="chip">Top Rated</span></div><div className="discoverGrid">{games.map(g=><GameCard game={g} key={g.name}/>)}</div>{games.length===0&&<div className="empty">No experiences found.</div>}</>}
function AvatarScreen({name}:{name:string}){return <><h1>Avatar</h1><div className="avatarStage"><div className="avatarFigure"><div className="head">{name.slice(0,1)}</div><div className="body"/></div><div><strong>{name}</strong><p className="muted">Classic simulated avatar</p></div></div><div className="card"><b>Customize</b><div className="customGrid">{['Body','Clothing','Accessories','Animations'].map(x=><button key={x}>{x}<span>›</span></button>)}</div></div></>}
function Profile({name,display,robux,description,onEdit}:{name:string;display:string;robux:number;description:string;onEdit:()=>void}){return <><div className="profileHead"><div className="bigAvatar">{display.slice(0,1)}</div><h1>{display}</h1><p className="muted">@{name}</p><button className="outlineBtn" onClick={onEdit}>Edit Profile</button></div><div className="stats"><div><b>128</b><span>Friends</span></div><div><b>542</b><span>Followers</span></div><div><b>91</b><span>Following</span></div></div><div className="card"><b>About</b><p>{description}</p><span className="pill">R$ {robux.toLocaleString()}</span></div><div className="card"><b>Inventory</b><p className="muted">Your simulated inventory will appear here.</p></div></>}
function SectionTitle({title,action,onClick}:{title:string;action:string;onClick:()=>void}){return <div className="sectionTitle"><h2>{title}</h2><button onClick={onClick}>{action}</button></div>}
function GameCard({game}:{game:Game}){return <button className="gameCard"><div className="thumb"><span>▰</span></div><b>{game.name}</b><small>{game.genre}</small><small className="muted">{game.players} playing</small></button>}
function GameRow({game}:{game:Game}){return <button className="gameRow"><div className="miniThumb">▰</div><div><b>{game.name}</b><small>{game.genre}</small><small className="muted">{game.players} playing</small></div><span>›</span></button>}
function Sheet({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay" onClick={close}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="grab"/><div className="sheetHead"><b>{title}</b><button onClick={close}>×</button></div>{children}</div></div>}
function SheetRow({icon,title,sub,onClick}:{icon:string;title:string;sub:string;onClick:()=>void}){return <button className="sheetRow" onClick={onClick}><span className="sheetIcon">{icon}</span><span><b>{title}</b><small>{sub}</small></span><i>›</i></button>}
